# Generated by Django 5.1.7 on 2025-04-11 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0002_specialattendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialattendance',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='specialattendance',
            name='teacher',
        ),
        migrations.AddField(
            model_name='specialattendance',
            name='student',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='teacher_app.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialattendance',
            name='subject',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='teacher_app.subject'),
            preserve_default=False,
        ),
    ]
