# Generated by Django 5.1.7 on 2025-04-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0003_remove_specialattendance_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialattendance',
            name='month',
        ),
        migrations.RemoveField(
            model_name='specialattendance',
            name='percentage',
        ),
        migrations.AlterField(
            model_name='specialattendance',
            name='date_submitted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
