# Generated by Django 5.1.7 on 2025-04-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0005_alter_attendancerecord_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='division',
            field=models.CharField(max_length=100),
        ),
    ]
