# Generated by Django 5.1.7 on 2025-04-12 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_subject_alter_student_roll_number_attendancerecord'),
        ('teacher_app', '0006_alter_teacher_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_attendance', to='student_app.student'),
        ),
    ]
