# Generated by Django 5.1.7 on 2025-04-13 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_delete_teacher_alter_attendancerecord_status_and_more'),
        ('teacher_app', '0008_alter_attendancerecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='GenerateReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attendance', models.IntegerField()),
                ('report_generated_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_app.teacher')),
            ],
        ),
    ]
