# Generated by Django 5.1.7 on 2025-04-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0009_alter_teacher_name_generatereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialattendance',
            name='month',
            field=models.CharField(choices=[('Month1', 'Month1'), ('Month2', 'Month2'), ('Month3', 'Month3'), ('Month4', 'Month4')], default='Month1', max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='division',
            field=models.CharField(max_length=10),
        ),
    ]
