# Generated by Django 5.1.7 on 2025-04-13 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0010_specialattendance_month_alter_teacher_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatereport',
            name='assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher_app.assessment'),
        ),
        migrations.AddField(
            model_name='generatereport',
            name='special_attendance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher_app.specialattendance'),
        ),
    ]
