# Generated by Django 5.1.7 on 2025-04-14 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0005_specialattendance'),
        ('teacher_app', '0012_alter_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_special_attendance', to='student_app.student'),
        ),
    ]
