# Generated by Django 5.1.7 on 2025-04-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0014_alter_attendancerecord_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='division',
            new_name='class_division',
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='default_password', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
