# Generated by Django 5.1.7 on 2025-04-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0016_specialattendance_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='pr_or',
        ),
        migrations.AddField(
            model_name='assessment',
            name='or_marks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment',
            name='pr_marks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
