# Generated by Django 5.2 on 2025-04-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0017_remove_assessment_pr_or_assessment_or_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialattendance',
            name='extra_option_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specialattendance',
            name='extra_option_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specialattendance',
            name='extra_option_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specialattendance',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
