# Generated by Django 5.2 on 2025-04-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0018_specialattendance_extra_option_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='semester',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
