# Generated by Django 5.2 on 2025-04-21 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0019_teacher_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='semester',
        ),
    ]
