# Generated by Django 5.1.7 on 2025-04-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_delete_teacher_alter_attendancerecord_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='division',
            field=models.CharField(default='A', max_length=10),
            preserve_default=False,
        ),
    ]
