# Generated by Django 5.1.7 on 2025-04-14 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0005_specialattendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialattendance',
            name='is_present',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='code',
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='specialattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='division',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(max_length=10),
        ),
    ]
