# Generated by Django 5.1.7 on 2025-04-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0009_totalattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalattendance',
            name='attendance_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='totalattendance',
            name='lectures_attended',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='totalattendance',
            name='total_lectures',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
