# Generated by Django 5.1.7 on 2025-04-17 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0010_totalattendance_attendance_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalattendance',
            name='attendance_percentage',
        ),
        migrations.AlterField(
            model_name='student',
            name='division',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='totalattendance',
            name='lectures_attended',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='totalattendance',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.subject'),
        ),
        migrations.AlterField(
            model_name='totalattendance',
            name='total_lectures',
            field=models.PositiveIntegerField(),
        ),
    ]
