# Generated by Django 5.1.7 on 2025-04-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0011_remove_totalattendance_attendance_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
