# Generated by Django 5.1.7 on 2025-04-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0012_alter_student_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('Pre-requisite Marks', 'Pre-requisite Marks'), ('Unit Test 1 Marks', 'Unit Test 1 Marks'), ('Unit Test 2 Marks', 'Unit Test 2 Marks'), ('Unit Test 3 Marks', 'Unit Test 3 Marks'), ('Insem Marks', 'Insem Marks'), ('Practical Marks', 'Practical Marks'), ('Oral Marks', 'Oral Marks')], max_length=50),
        ),
    ]
