# Generated by Django 5.2 on 2025-04-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0013_alter_assessment_assessment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialattendance',
            name='date',
        ),
        migrations.AddField(
            model_name='specialattendance',
            name='lectures_attended',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialattendance',
            name='total_lectures',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
