from student_app.models import Student

students_data = [
    ("Adhav Amruta Vikas", 1, "A"),
    ("Akshit Somkure", 2, "A"),
    ("Aniket Dattatray Thorat", 3, "A"),
    ("Aranye Sneha Santosh", 4, "A"),
    ("Athani Bhimashankar Chandrashekhar", 5, "A"),
    ("Babar Yashraj Datta", 6, "A"),
    ("Bagade Harsh Babasaheb", 7, "A"),
    ("Bandal Viraj Sachin", 8, "A"),
    ("Bhalerao Bhakti Rajendra", 9, "A"),
    ("Bhandare Harshada Ashok", 10, "A"),
    ("Bhandari Pawan Singh Jagdish", 11, "A"),
    ("Bhise Vishal Mahalu", 12, "A"),
    ("Bhoomi Kushwah", 13, "A"),
    ("Bhosale Akansha Anandrao", 14, "A"),
    ("Bhosale Samarth Shailesh", 15, "A"),
    ("Bhosure Pranali Santosh", 16, "A"),
    ("Bonde Kajal Sandip", 17, "A"),
    ("Borude Sneha Chandrakant", 18, "A"),
    ("Bramhankar Rahul Husen", 19, "A"),
    ("Chavan Durvankur Nitin", 20, "A"),
    ("Chede Omkar Anil", 21, "A"),
    ("Choudhari Sakshi Dattatraya", 22, "A"),
    ("Dambare Tejashree Bhausaheb", 23, "A"),
    ("Darade Snehal Shahadev", 24, "A"),
    ("Deshmukh Vansh Manoj", 25, "A"),
    ("Dhage Tejasvi Santosh", 26, "A"),
    ("Dhumal Ashwini Rajendra", 27, "A"),
    ("Dhumal Dhanashri Santosh", 28, "A"),
    ("Dhumal Jaydeep Machhindra", 29, "A"),
    ("Divate Payal Bhausaheb", 30, "A"),
    ("Doke Pratik Bhausaheb", 31, "A"),
    ("Dolas Bodhini Bimbeesar", 32, "A"),
    ("Dukare Shrey Nagsen", 33, "A"),
    ("Duttargi Poornima Malleshappa", 34, "A"),
    ("Funde Puja Pankaj", 35, "A"),
    ("Gadade Komal Rangnath", 36, "A"),
    ("Gade Shrutika Vinod", 37, "A"),
    ("Gaikwad Nandkumar Vinayak", 38, "A"),
    ("Gajare Vibhawari Santosh", 39, "A"),
    ("Gajare Yash Mahendra", 40, "A"),
    ("Gavale Mohini Chandoba", 41, "A"),
    ("Gawade Ganesh Shivaji", 42, "A"),
    ("Gawali Rohit Sunil", 43, "A"),
    ("Ghadage Ajay Sadanand", 44, "A"),
    ("Ginjal Avishkar Sopan", 45, "A"),
    ("Wable Rohit Suresh", 46, "A"),
    ("Ayush Rajdatta Suryavanshi", 47, "A"),
    ("Chandana Vinayak Tikare", 48, "A"),
    ("Bodkhe Harsh Sanjay", 49, "A"),
    ("Deshmukh Riya Vilasrao", 50, "A"),
    ("Dhanashri Rangnath Gundal", 51, "A"),
    ("Dhepe Vaibhavi Bhaskar", 52, "A"),
    ("Dighe Yashshree Rahul", 53, "A"),
    ("Divyansh Srivastava", 54, "A"),
    ("Gaikwad Rohit Pandurang", 55, "A"),
    ("Ghodke Shrinath Laxman", 56, "A"),
    ("Giri Harshada Harigeer", 57, "A"),
    ("Giri Vedant Madhav", 58, "A"),
    ("Gunjal Sujit Dhondiba", 59, "A"),
    ("Jadhav Rohit Balaso", 60, "A"),
    ("Tupkar Rutik Gajanan", 61, "A"),
    ("Korekar Akshay Rajendra", 62, "A"),
    ("Vishal Laxman Choudhar", 63, "A"),
    ("Ayaan Sallauddin Kazi", 64, "A"),
    ("Hargude Shruti Shivaji", 65, "A"),
    ("Rajput Pruthviraj Rajendra Sing", 66, "A"),
    ("Patil Pravin Sunil", 67, "A"),
    ("Bhujbal Dhanashri Satyawan", 68, "A"),
    ("Kolhe Ankita Dhananjay", 69, "A"),
    ("Navale Bhumika Mahabaleshwar", 70, "A"),
    ("Shivale Pruthviraj Laxman", 71, "A"),
    ("Rajput Saloni Kishor", 72, "A"),
    ("Chaudhari Om Kedar", 73, "A"),
]

for student in students_data:
    Student.objects.create(name=student[0], roll_number=student[1], division=student[2])
